// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: message.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
   message, user_id, parent_id, room_id
) values (
    $1, $2, $3, $4
) RETURNING id, message, user_id, parent_id, likes_count, answered, room_id, created_at, updated_at
`

type CreateMessageParams struct {
	Message  pgtype.Text `json:"message"`
	UserID   pgtype.Int8 `json:"user_id"`
	ParentID pgtype.Int8 `json:"parent_id"`
	RoomID   pgtype.Int8 `json:"room_id"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.Message,
		arg.UserID,
		arg.ParentID,
		arg.RoomID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Message,
		&i.UserID,
		&i.ParentID,
		&i.LikesCount,
		&i.Answered,
		&i.RoomID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
