// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: message.sql

package db

import (
	"context"
	"database/sql"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
   message, user_id, parent_id, room_id
) values (
    $1, $2, $3, $4
) RETURNING id, message, user_id, parent_id, likes_count, answered, room_id, created_at, updated_at
`

type CreateMessageParams struct {
	Message  sql.NullString `json:"message"`
	UserID   int64          `json:"user_id"`
	ParentID sql.NullString `json:"parent_id"`
	RoomID   int64          `json:"room_id"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.Message,
		arg.UserID,
		arg.ParentID,
		arg.RoomID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Message,
		&i.UserID,
		&i.ParentID,
		&i.LikesCount,
		&i.Answered,
		&i.RoomID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM messages
WHERE id=$1
`

func (q *Queries) DeleteMessage(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteMessage, id)
	return err
}

const getMessage = `-- name: GetMessage :one
SELECT id, message, user_id, parent_id, likes_count, answered, room_id, created_at, updated_at FROM messages
WHERE id=$1 LIMIT 1
`

func (q *Queries) GetMessage(ctx context.Context, id int64) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Message,
		&i.UserID,
		&i.ParentID,
		&i.LikesCount,
		&i.Answered,
		&i.RoomID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMessages = `-- name: ListMessages :many
SELECT id, message, user_id, parent_id, likes_count, answered, room_id, created_at, updated_at FROM messages
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListMessagesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessages, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.Message,
			&i.UserID,
			&i.ParentID,
			&i.LikesCount,
			&i.Answered,
			&i.RoomID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAnswered = `-- name: UpdateAnswered :one
UPDATE messages 
SET answered = $2 
WHERE id=$1
RETURNING id, message, user_id, parent_id, likes_count, answered, room_id, created_at, updated_at
`

type UpdateAnsweredParams struct {
	ID       int64        `json:"id"`
	Answered sql.NullBool `json:"answered"`
}

func (q *Queries) UpdateAnswered(ctx context.Context, arg UpdateAnsweredParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, updateAnswered, arg.ID, arg.Answered)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Message,
		&i.UserID,
		&i.ParentID,
		&i.LikesCount,
		&i.Answered,
		&i.RoomID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLikes = `-- name: UpdateLikes :one
UPDATE messages 
SET likes_count = $2 
WHERE id=$1
RETURNING id, message, user_id, parent_id, likes_count, answered, room_id, created_at, updated_at
`

type UpdateLikesParams struct {
	ID         int64         `json:"id"`
	LikesCount sql.NullInt64 `json:"likes_count"`
}

func (q *Queries) UpdateLikes(ctx context.Context, arg UpdateLikesParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, updateLikes, arg.ID, arg.LikesCount)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Message,
		&i.UserID,
		&i.ParentID,
		&i.LikesCount,
		&i.Answered,
		&i.RoomID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMessage = `-- name: UpdateMessage :one
UPDATE messages 
SET message = $2 
WHERE id=$1
RETURNING id, message, user_id, parent_id, likes_count, answered, room_id, created_at, updated_at
`

type UpdateMessageParams struct {
	ID      int64          `json:"id"`
	Message sql.NullString `json:"message"`
}

func (q *Queries) UpdateMessage(ctx context.Context, arg UpdateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, updateMessage, arg.ID, arg.Message)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Message,
		&i.UserID,
		&i.ParentID,
		&i.LikesCount,
		&i.Answered,
		&i.RoomID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateParent = `-- name: UpdateParent :one
UPDATE messages 
SET parent_id = $2 
WHERE id=$1
RETURNING id, message, user_id, parent_id, likes_count, answered, room_id, created_at, updated_at
`

type UpdateParentParams struct {
	ID       int64          `json:"id"`
	ParentID sql.NullString `json:"parent_id"`
}

func (q *Queries) UpdateParent(ctx context.Context, arg UpdateParentParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, updateParent, arg.ID, arg.ParentID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Message,
		&i.UserID,
		&i.ParentID,
		&i.LikesCount,
		&i.Answered,
		&i.RoomID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
