// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Message struct {
	ID int64 `json:"id"`
	// Content of the post
	Message    pgtype.Text        `json:"message"`
	UserID     pgtype.Int8        `json:"user_id"`
	ParentID   pgtype.Int8        `json:"parent_id"`
	LikesCount pgtype.Int8        `json:"likes_count"`
	Answered   pgtype.Bool        `json:"answered"`
	RoomID     pgtype.Int8        `json:"room_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Room struct {
	ID        int64              `json:"id"`
	UserID    pgtype.Int8        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID        int64              `json:"id"`
	Username  string             `json:"username"`
	Password  string             `json:"password"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
