// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Message struct {
	ID int64 `json:"id"`
	// Content of the post
	Message    sql.NullString `json:"message"`
	UserID     int64          `json:"user_id"`
	ParentID   sql.NullString `json:"parent_id"`
	LikesCount sql.NullInt64  `json:"likes_count"`
	Answered   sql.NullBool   `json:"answered"`
	RoomID     int64          `json:"room_id"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	UpdatedAt  sql.NullTime   `json:"updated_at"`
}

type Room struct {
	ID        int64        `json:"id"`
	UserID    int64        `json:"user_id"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type User struct {
	ID        int64        `json:"id"`
	Username  string       `json:"username"`
	Password  string       `json:"password"`
	Email     string       `json:"email"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}
