# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: ci-test

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    services: 
      postgres: 
        image: postgres:latest
        env: 
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: ama
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --healthretries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.1'
      id: go

    - name: Install golang-migrate
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.18.1/migrate.darwin-arm64.tar.gz | tar xvz
        mv migrate.linux-amd64 /usr/bin
        which migrate

    - name: Run migrations
      run: make migrateup

    - name: Test
      run: make test